### ISSUE TITLE
bug when typing lower case character

### ISSUE THREAD

**Issue by zymiboxpay** [tjgrathwell/typer_tortoise#1]
I found a bug when I miss typed a upper case character in a snippet begins with " from SOAPpy import WSDL.....", this snippet belongs in python Category.

When I typed the second line begins with 

"WSDLFILE = '/path/to/copy/of/GoogleSearch.wsdl' "

I miss typed the first character "W" with a lower case "w", and then I couldn't deleted it anymore.

**Comment by tjgrathwell** [comment]
Great find @zymiboxpay, I've fixed and redeployed. Thanks a lot!

**Comment by zymiboxpay** [comment]
@tjgrathwell I like this game. You are welcome.
